### ISSUE TITLE
Binder fails to build

### ISSUE THREAD

**Issue by jtpio** [robots-from-jupyter/robotframework-jupyterlibrary#29]
Looks like the Binder is currently failing to build with the following:

![image](https://user-images.githubusercontent.com/591645/104485021-44259300-55ca-11eb-89d6-3d8b29e04fc6.png)

Maybe it's a matter of regenerating the `conda.lock` file.

**Comment by bollwyvl** [comment]
Thanks. I should really set up a cron. It's probably all the `rc` channels fighting...

I intend to circle back around with this, certainly have found some more sharp edges that could be better integrated:

- https://github.com/deathbeds/wxyz/pull/50
- https://github.com/deathbeds/jupyterlab-starters/pull/51
- https://github.com/krassowski/jupyterlab-lsp/pull/452

Will probably add jupyterlab-classic as well... hopefully it can special-case Lab or something, as a pattern going forward:
- https://github.com/krassowski/jupyterlab-lsp/pull/465

**Comment by bollwyvl** [comment]
Thanks for the fix on #30 for this @jtpio! I wonder if it's worth putting the CI on a nightly to keep this in check. In the future, we'll probably just want to make sure an `rc` upstream is not the _default_ demo branch :grimacing: 

Please reopen if anything else crops up, and maybe I can get something else working to do a nightly check.
