### ISSUE TITLE
Keyword "Add and Run JupyterLab Code Cell" fails with ElementNotInteractableException when more than one file is open

### ISSUE THREAD

**Issue by LaVLaS** [robots-from-jupyter/robotframework-jupyterlibrary#36]
### Description of the problem:
When executing the keyword `Add and Run JupyterLab Code Cell` when multiple files are open in JupyterLab an `ElementNotInteractableException` will be thrown.

```
Clicking element 'xpath://div[contains(@class, 'jp-NotebookPanel-toolbar')]//*[@data-icon='ui-components:add']'
ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=88.0.4324.150)
```

### Expected behavior:
`Add and Run JupyterLab Code Cell` will add and run a new cell in notebook file tab that is open for editing

### Possible Solution
When searching for the element `//div[contains(@class, 'jp-NotebookPanel-toolbar')]//*[@data-icon='ui-components:add']` use the currently selected/visible notebook as the root

### Package Versions:
JupyterLab v3.0.7
robotframework==4.0
robotframework-jupyterlibrary==0.3.0
robotframework-seleniumlibrary==5.1.3

### Workaround:
Close all other files that are open in the NotebookPanel for browser

**Comment by bollwyvl** [comment]
@LaVLaS sorry it took a month to get around to this, but it just shipped in 0.3.1... please let me know if there's anything else that gets us into trouble with multiple documents!
