### ISSUE TITLE
"Add and Run JupyterLab Code Cell" keyword throws error intermittently

### ISSUE THREAD

**Issue by chidambaranathan-r** [robots-from-jupyter/robotframework-jupyterlibrary#58]
robotframework==4.0.3
robotframework-jupyterlibrary==0.3.1
Jupyterlab version: 3.2.8

**Observation**:

While we try to use the keyword "Add and Run JupyterLab Code Cell", sometimes it works and sometimes it throws the below error:

```
ElementNotInteractableException: Message: Element <svg> could not be scrolled into view
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.jsm:293:5
webdriverClickElement@chrome://remote/content/marionette/interaction.js:156:11
interaction.clickElement@chrome://remote/content/marionette/interaction.js:125:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:203:24
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:91:31
```

Attached the screenshots for reference.
![Screenshot_1](https://user-images.githubusercontent.com/1535689/157255143-772d9600-7766-4bf8-8c4d-fe6f70c5ccb8.png)
![Screenshot_2](https://user-images.githubusercontent.com/1535689/157255155-e78a96a2-3c73-4864-a46b-66161c0c4a4d.png)

**Comment by bollwyvl** [comment]
It's probably trying to click on the run button in the notebook behind it. #47 theoretically fixes these, but still has a ways to go.

For now, if you ensure you only have one notebook open, it should work more reliably.

**Comment by chidambaranathan-r** [comment]
Thank you for the suggestion @bollwyvl 

I used the keyword "Close All JupyterLab Tabs" in all the test case as a teardown, to ensure when a test case runs, it will have its own (one and only) notebook. I guess, it helped to overcome the above challenge that I reported.

**Comment by chidambaranathan-r** [comment]
As using "Close All JupyterLab Tabs" solved my issue, closing this comment.
Will follow-up on the https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/pull/47
