### ISSUE TITLE
Re-run tests to verify function with jupyter_server 2 now released

### ISSUE THREAD

**Issue by consideRatio** [robots-from-jupyter/robotframework-jupyterlibrary#65]
I'm not grasping how everything works, but I think there is a test suite setup in this repo to run a test involving jupyter_server. Can we run that test suite now that jupyter_server 2 is out and see if it succeeds, or if there is something to fix in this repo?

I was led to think about this as I observed the failure noticed "parent suite setup failed" and was thinking perhaps that was related to this repo rather than the failing test in the jupyterhub/jupyter-server-proxy relying on this project.

![image](https://user-images.githubusercontent.com/3837114/210067527-4303b760-c189-49b7-958b-aba2daea2339.png)

## Related source code in this repo

https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/660ef6661aafd0c1f0f79e6a61443301831eb3df/.github/env_specs/lab3.yml#L5-L6

https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/660ef6661aafd0c1f0f79e6a61443301831eb3df/.github/workflows/ci.yml#L141-L154

**Comment by consideRatio** [comment]
## I ran tests in a fork

- It seems that the tests pass, **but**, that only jupyter_server 1 (1.21) was used: https://github.com/consideRatio/robotframework-jupyterlibrary/actions/runs/3807172663/jobs/6476620493#step:6:1077
- conda-forge has jupyter_server 2 out also, so its not conda-forge lagging behind that caused this (https://anaconda.org/conda-forge/jupyter_server).
- It seems that jupyterlab 3.4.8 was used, and only 3.5.0 accepts jupyter_server 2: https://github.com/consideRatio/robotframework-jupyterlibrary/actions/runs/3807172663/jobs/6476620493#step:6:1105.
- I think its caused by installing retrolab, which in turn require jupyter_server 1: https://github.com/jupyterlab/retrolab/blob/a8ff891b4a17ef0359e76b9697ecb5af0a53dc66/setup.cfg#L30-L35
- Oh, version controlled lock files in .github/lock - they need to be updated

## Lock files needs to be updated

@bollwyvl could you update the lock files so we can test with jupyter_server 2 here? I'm not sure how to do that atm.

Related but off topic: a practice I've come to appreicate to help others onboard people in projects is to co-locate a README.md file that very briefly (~1 paragraph) links to relevant tools and mentions a command to run or so. If you update these files, maybe you can create a README.md to help someone like me onboard to contribute with such chore tasks?

**Comment by bollwyvl** [comment]
yep, there's not a ton to do (basically update the spec file for lab3) but actually adding another dimension is non-trivial.

> README.md

That would be the [`CONTRIBUTING.md`](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/blob/master/CONTRIBUTING.md) and section of the [docs](https://robotframework-jupyterlibrary.readthedocs.io/en/stable/INSTALL.html#contributing-to-jupyterlibrary).

**Comment by consideRatio** [comment]
Ah thank you, i can trial out things later then! Have a good new year @bollwyvl!

**Comment by bollwyvl** [comment]
from the ci pr: i think the issue is we _do_ need to keep lab3 vs server1, irrespective of python version, which we'll likely drop in the next release, anyway.

we should probably drop retrolab entirely, as it is no longer receiving updates, though i was waiting until notebook 7 became available to make that shift.
